### ISSUE TITLE
homebridge-kevo suddenly crashes homebridge

### ISSUE THREAD

**Issue by geofbuck** [nfarina/homebridge-kevo#18]
here is the printout from terminal (mac) no other changes just crashed today and can't restart homebridge, tried reinstall/update.

/usr/local/lib/node_modules/homebridge-kevo/index.js:66
    if (response.statusCode == 302) return; // we cancelled a redirect above
                 ^
TypeError: Cannot read property 'statusCode' of undefined
    at KevoAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-kevo/index.js:66:18)
    at self.callback (/usr/local/lib/node_modules/homebridge-kevo/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-kevo/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Plex-Media-S

**Comment by petsche** [comment]
I have the same problem. It seems that the API used by this plugin is the same as the interactive website and they just added a captcha on the website. Another thread that tries to do a similar thing is below. I am just a user of these homebridge plugins, not really a developer on them, so unfortunately I do not have any advice on how to overcome this.
https://community.smartthings.com/t/kevo-plus-device-type-dth-link-in-post-18/36198/61?u=gaduran3

**Comment by pmeisel123** [comment]
This was caused by the captcha being added
https://github.com/nfarina/homebridge-kevo/issues/17

Looks like the captcha issue is been fixed by kevo

**Comment by geofbuck** [comment]
Sweet! Thanks for the heads up, I added it back into my config and it seems to be working fine now. I find it interesting how it when it was down it still worked with Alexa but only from alexa devices and for iphone you could lock but not unlock. Must be a security issue stipulation for integration with Kevo.

**Comment by geofbuck** [comment]
Nope its back again. It causing my homebridge setup to crash unless I remove it

**Comment by geofbuck** [comment]
Here is the error:

[Back Door] Getting current state...
[2019-8-3 20:10:18] [Back Door] Getting current state...
[2019-8-3 20:11:07] TypeError: Cannot read property 'statusCode' of undefined
    at KevoAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-kevo/index.js:66:18)
    at self.callback (/usr/local/lib/node_modules/homebridge-kevo/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-kevo/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2019-8-3 20:11:07] Got SIGTERM, shutting down Homebridge...

**Comment by Tiger519** [comment]
I kind of want to say this is just an intermittent issue, but it might be possible to ignore the error and at least stop homebridge from crashing. This sounds familiar and I almost feel like I fixed this on a fork I did years ago... Will have to check and see if it is possible to get around the error.

**Comment by Tiger519** [comment]
So something that might help, the issue here, beyond not getting the API response, is that `response` is undefined, so trying to access `response.statusCode` is an uncaught error and crashing Homebridge. I have run into a similar issue in my day job. Node.js version 14+ supports optional chaining, so we could instead reference `response?.statusCode`, which will just be undefined instead of throwing an uncaught error. But I'm not sure if it's safe to or if we should assume v14.x. Until this latest install I think I was running v6.x.... Or I suppose an old fashioned ` if (response) { if (response.statusCode == ...` would work without the implcation of the node version.

**Comment by pmeisel123** [comment]
As I have posted in other threads, the problem is with the KEVO CAPTCHA.

If you login to kevo from any browser, and then close the browser (**without logging out**), then the homebridge app can login without filling out the CAPTCHA.

Not sure if this was intentional on KEVO part or just a lucky break, but it seems to work

**Comment by fab301s** [comment]
> As I have posted in other threads, the problem is with the KEVO CAPTCHA.
> 
> If you login to kevo from any browser, and then close the browser (**without logging out**), then the homebridge app can login without filling out the CAPTCHA.
> 
> Not sure if this was intentional on KEVO part or just a lucky break, but it seems to work

I have seen your other posts, however unfortunately that has not worked for me :(

**Comment by pmeisel123** [comment]
> > As I have posted in other threads, the problem is with the KEVO CAPTCHA.
> > If you login to kevo from any browser, and then close the browser (**without logging out**), then the homebridge app can login without filling out the CAPTCHA.
> > Not sure if this was intentional on KEVO part or just a lucky break, but it seems to work
> 
> I have seen your other posts, however unfortunately that has not worked for me :(

Sorry to hear.  It is a real pain to debug this problems.  Usually login in via the browser fixes the issue.  Though I also recommend having a separate kevo account for each lock, and to use a yet another account for your kevo app.  If you fail to login too many times, kevo will sometimes lock the account out.  And homebridge-kevo will retry to login if it fails.  So it can cause your account to get locked.   As long as your primary account still works, it is easy to create new accounts and replace the dead ones

I posted in https://github.com/nfarina/homebridge-kevo/issues/17 my tweaks to the code though as I stated there, it has been a while since I touched my local copy.  My only problem lately was my kevo plus kept going offline (which causes weird issues with homebridge-kevo).  Actually had to buy a second kevo plus.  On the plus side I did find out you can have 2 kevo plus on the same wifi network.

**Comment by Tiger519** [comment]
@pmeisel123 interesting, I continually get the "Submit login failed with status 200" errors, but the plugin still works for me. Until yesterday, I probably hadn't logged in to Kevo web portal in several years (I do have the app on my phone, no idea if that has anything to do with it. it's a different login account, though, so I doubt it).

**Comment by pmeisel123** [comment]
> @pmeisel123 interesting, I continually get the "Submit login failed with status 200" errors, but the plugin still works for me. Until yesterday, I probably hadn't logged in to Kevo web portal in several years (I do have the app on my phone, no idea if that has anything to do with it. it's a different login account, though, so I doubt it).

Ohh!!!  I had forgotten that (haven't looked at my logs in a while either).  With the "Captcha hack" it gets an error when logging in (because you didn't have the captcha), but it gives you the cookies anyway.  Originally I thought you had to login regularly to keep the captcha hack working, but over time I realized I could go a very long time without logging in.

BTW you can test this.  Login to kevo, then in an incognito window login without the captcha (you will fail and land on the login screen).  Then go to https://www.mykevo.com/user/locks and you will see you are logged in 

Kevo didn't always have the captcha, (homebridge-kevo was built before the captcha was added).  I suspect (or more like wildly guessing), that when kevo added the captcha, all they did was add a flag on the user to say if they had passed or failed the captcha.  When you login, it sets the cookies, then it test the captcha.  If you pass the captcha it sets the flag to pass. When you logout it sets it to not passed.  When you login without filling in the captcha it doesn't do anything to the flag.  So if you login from your browser, and just close the browser, your captcha's never gets flagged to off.  Then when homebridge-kevo logs in it fails the captcha, but still gets the cookies, but doesn't update the flag.
