### ISSUE TITLE
Unexpected  status code 401

### ISSUE THREAD

**Issue by LwsBtlr** [nfarina/homebridge-kevo#20]
Kevo is setup and shows up in Home until I try to unlock or lock, at which point I get the following and then the lock is set to “no response” until I restart homebridge.

```
1/21/2020, 2:40:37 PM] [Front] Lock status is Locked
[1/21/2020, 2:40:43 PM] [Front] Already logged in.
[1/21/2020, 2:40:43 PM] [Front] Setting status to Unlocked
[1/21/2020, 2:40:43 PM] [Front] Error setting state: Error: Unexpected status_code 401
    at KevoAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-kevo/index.js:200:18)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-kevo/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-kevo/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:321:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-kevo/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:427:28)
    at IncomingMessage.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by LwsBtlr** [comment]
(sorry about formatting, it looked correct in the preview) ¯\_(ツ)_/¯

**Comment by fab301s** [comment]
Just began receiving this error, despite it working fine for many months
