### ISSUE TITLE
Error submitting login page: Error: Bad status code 200

### ISSUE THREAD

**Issue by SemoTech** [nfarina/homebridge-kevo#21]
Using a Kwikset 99250-206 Kevo Contemporary Touch-to-Open Bluetooth Smart Square Door Lock Deadbolt.  Firmware v1.9.49

Platform:  Raspberry Pi 4b | Homebridge v1.3.6 | NPM v6.1.3 | Node.Js v16.13.0
Plugin: homebridge-kevo v0.0.3

Seems the Kevo plugin is unable to login/communicate with the Kevo servers, or something has changed on the server, and the plugin needs to be updated. I am able to login into the site manually with the same credentials, so it is not a mistyped credential issue. 

Here is the relevant excerpt from the log related to the Kevo plugin:

```
[10/11/2021, 06:44:45] ---
[10/11/2021, 06:44:45] Loaded plugin: homebridge-kevo@0.0.3
[10/11/2021, 06:44:45] Registering accessory 'homebridge-kevo.Kevo'
[10/11/2021, 06:44:45] ---
[10/11/2021, 06:44:47] [Office Kevo Lock] Initializing Kevo accessory...
[10/11/2021, 06:45:03] [Office Kevo Lock] Getting current state...
[10/11/2021, 06:45:03] [Kevo Lock] Error submitting login page: Error: Bad status code 200
    at KevoAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-kevo/index.js:101:24)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-kevo/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-kevo/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-kevo/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[10/11/2021, 06:45:03] [Kevo Lock] There was a problem logging into Kevo. Check your username and password.
```

Any suggestions to fix or possibly use a different plugin if this one cannot be updated to be compatible?

**Comment by joshua-small** [comment]
I thought I was also experiencing this issue, but apparently, I had changed my Kevo password at some point since configuring this plugin. It is currently working for me. Here are my system details:

| Lock | Firmware version | Platform | OS | Homebridge version | npm version | nodeJS version | homebridge-kevo plugin version |
| :- | :- | :- | :- | :- | :- | :- | :- |
| Kwikset 99250-202 Kevo 2nd Gen | 1.9.49 | Dell OptiPlex 7070 | Ubuntu 21.10 | 1.3.8 | 8.1.4 | 16.13.0 | 0.0.3 |

Here is the Kevo plugin snippet from the Homebridge log from when the plugin could not login:

```
[11/30/2021, 10:45:52 AM] [Front Door] Error submitting login page: Error: Bad status code 200
    at KevoAccessory.<anonymous> (/usr/lib/node_modules/homebridge-kevo/index.js:101:24)
    at Request.self.callback (/usr/lib/node_modules/homebridge-kevo/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-kevo/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-kevo/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[11/30/2021, 10:45:52 AM] [Front Door] There was a problem logging into Kevo. Check your username and password.
```

@SemoTech, consider updating Homebridge to version 1.3.8 and npm to version 8.1.4. Also consider changing your Kevo password and trying again. I know that passwords with certain special characters stored as plaintext string in JSON can sometimes have issues without escaping the characters, depending on how the code parsing the JSON handles the string.

**Comment by SemoTech** [comment]
@joshua-small Thanks.  So same setup as mine (I am already running latest homebridge and npm) but maybe it's a password issue.  I will try a simpler one...

**Comment by SemoTech** [comment]
@joshua-small I changed/simplified the password but no luck, same "code 200 error". Password is no spaces, just letters and numbers, no symbols.  

And  the lock is showing/saying its unlocked even tho it is locked and it's own Kivo iOS app confirms it.  Pressing "lock" seems to work in HK for a minute (nothing happens at the physical lock) then it virtually "unlocks" itself and shows as "unlocked" again in the logs and HK!   Are you having same issues?

```
[01/12/2021, 17:56:31] [Office Door] Error submitting login page: Error: Bad status code 200
    at KevoAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-kevo/index.js:101:24)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-kevo/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-kevo/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-kevo/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[01/12/2021, 17:56:31] [Office Door] There was a problem logging into Kevo. Check your username and password.
[01/12/2021, 17:56:53] [Office Door] Getting current state...
[01/12/2021, 17:56:53] [Office Door] Getting current state...
[01/12/2021, 17:56:53] [Office Door] Getting current state...
[01/12/2021, 17:56:53] [Office Door] Getting current state...
[01/12/2021, 17:56:54] [Office Door] Already logged in.
[01/12/2021, 17:56:54] [Office Door] Already logged in.
[01/12/2021, 17:56:54] [Office Door] Already logged in.
[01/12/2021, 17:56:54] [Office Door] Already logged in.
[01/12/2021, 17:56:54] [Office Door] Lock status is Unlocked
[01/12/2021, 17:56:54] [Office Door] Lock status is Unlocked
[01/12/2021, 17:56:54] [Office Door] Lock status is Unlocked
[01/12/2021, 17:56:54] [Office Door] Lock status is Unlocked
[01/12/2021, 17:57:30] [Office Door] Already logged in.
[01/12/2021, 17:57:30] [Office Door] Setting status to Locked
[01/12/2021, 17:57:33] [Office Door] Getting current state...
[01/12/2021, 17:57:33] [Office Door] Getting current state...
[01/12/2021, 17:57:33] [Office Door] Already logged in.
[01/12/2021, 17:57:33] [Office Door] Already logged in.
[01/12/2021, 17:57:34] [Office Door] Lock status is Unlocked
[01/12/2021, 17:57:34] [Office Door] Lock status is Unlocked
[01/12/2021, 17:57:53] [Office Door] Already logged in.
[01/12/2021, 17:57:53] [Office Door] Setting status to Locked
[01/12/2021, 17:59:03] [Office Door] Getting current state...
[01/12/2021, 17:59:03] [Office Door] Getting current state...
[01/12/2021, 17:59:04] [Office Door] Already logged in.
[01/12/2021, 17:59:04] [Office Door] Already logged in.
[01/12/2021, 17:59:04] [Office Door] Lock status is Unlocked
[01/12/2021, 17:59:04] [Office Door] Lock status is Unlocked
```


Thanks.

**Comment by Tiger519** [comment]
I seem to recall getting this error for years. It doesn't seem to affect the overall functionality, though, as usually the next attempt you'll see the "Already logged in" message. Not sure if this is actually an issue with the API or if there is something in the code not handling some case on login (it is expecting a redirect but in these cases getting a 200, which although is a success code is not what the plugin is expecting). I just had to do a fresh install of homebridge so I have some renewed interest in this plugin, but on the whole it seems to be working ok so I'm not too motivated to try to fix this right now.

**Comment by fab301s** [comment]
> I seem to recall getting this error for years. It doesn't seem to affect the overall functionality, though, as usually the next attempt you'll see the "Already logged in" message. Not sure if this is actually an issue with the API or if there is something in the code not handling some case on login (it is expecting a redirect but in these cases getting a 200, which although is a success code is not what the plugin is expecting). I just had to do a fresh install of homebridge so I have some renewed interest in this plugin, but on the whole it seems to be working ok so I'm not too motivated to try to fix this right now.

Which version of Node are you running?

**Comment by Tiger519** [comment]
@fab301s my current install is running v14.18.1 with homebridge v1.4.0. Up until yesterday, I was running on an ancient build, v6.x with some really old homebridge version (maybe like 0.3.x?).
