### ISSUE TITLE
Kevo crashing homebridge 

### ISSUE THREAD

**Issue by danielsza** [nfarina/homebridge-kevo#25]
It looks like this issue started June 15th (for me).
Nothing was changed between june 15-18.

[18/06/2023, 12:11:33] [Front Door] Restarting Process...
[18/06/2023, 12:11:33] [Homebridge UI] Homebridge log truncated by admin.
[18/06/2023, 12:11:33] [Garage Door] Launched child bridge with PID 11024
[18/06/2023, 12:11:34] Registering accessory 'homebridge-kevo.Kevo'
[18/06/2023, 12:11:34] [Garage Door] Loaded homebridge-kevo v0.0.5 child bridge successfully
[18/06/2023, 12:11:34] Loaded 0 cached accessories from cachedAccessories.0E991DD1A59B.
[18/06/2023, 12:11:35] [Front Door] Launched child bridge with PID 11034
[18/06/2023, 12:11:35] Homebridge v1.6.1 (HAP v0.11.1) (Garage Door) is running on port 58488.

/var/lib/homebridge/node_modules/homebridge-kevo/index.js:66
    if (response.statusCode == 302) return; // we cancelled a redirect above
                 ^
TypeError: Cannot read properties of undefined (reading 'statusCode')
    at KevoAccessory.<anonymous> (/var/lib/homebridge/node_modules/homebridge-kevo/index.js:66:18)
    at self.callback (/var/lib/homebridge/node_modules/homebridge-kevo/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.onRequestError (/var/lib/homebridge/node_modules/homebridge-kevo/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[18/06/2023, 12:11:35] [Garage Door] Child bridge process ended
[18/06/2023, 12:11:35] [Garage Door] Process Ended. Code: 1, Signal: null
[18/06/2023, 12:11:35] Registering accessory 'homebridge-kevo.Kevo'
[18/06/2023, 12:11:35] [Front Door] Loaded homebridge-kevo v0.0.5 child bridge successfully
[18/06/2023, 12:11:35] Loaded 0 cached accessories from cachedAccessories.0E991DD1A59C.
[18/06/2023, 12:11:36] Homebridge v1.6.1 (HAP v0.11.1) (Front Door) is running on port 58588.

/var/lib/homebridge/node_modules/homebridge-kevo/index.js:66
    if (response.statusCode == 302) return; // we cancelled a redirect above
                 ^
TypeError: Cannot read properties of undefined (reading 'statusCode')
    at KevoAccessory.<anonymous> (/var/lib/homebridge/node_modules/homebridge-kevo/index.js:66:18)
    at self.callback (/var/lib/homebridge/node_modules/homebridge-kevo/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.onRequestError (/var/lib/homebridge/node_modules/homebridge-kevo/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[18/06/2023, 12:11:36] [Front Door] Child bridge process ended
[18/06/2023, 12:11:36] [Front Door] Process Ended. Code: 1, Signal: null

the issue remans after upgrading node.js
ℹ Updating Node.js from v18.13.0 to v18.16.0...
And Homebrige to v1.6.1, from v1.6.0

**Comment by mikeoc13** [comment]
Having same issue:

[6/19/2023, 12:02:22 PM] TypeError: Cannot read properties of undefined (reading 'statusCode')
    at KevoAccessory.<anonymous> (/volume1/homebridge/node_modules/homebridge-kevo/index.js:66:18)
    at self.callback (/volume1/homebridge/node_modules/homebridge-kevo/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.onRequestError (/volume1/homebridge/node_modules/homebridge-kevo/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[6/19/2023, 12:02:22 PM] Got SIGTERM, shutting down Homebridge...
[6/19/2023, 12:02:22 PM] [Nest] Child bridge process ended
[6/19/2023, 12:02:22 PM] [Nest] Process Ended. Code: null, Signal: SIGTERM
[6/19/2023, 12:02:27 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[6/19/2023, 12:02:32 PM] [HB Supervisor] Restarting Homebridge...
[6/19/2023, 12:02:32 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /volume1/homebridge/node_modules --strict-plugin-resolution
[6/19/2023, 12:02:32 PM] [HB Supervisor] Started Homebridge v1.6.0 with PID: 16658
[6/19/2023, 12:02:33 PM] Loaded config.json with 1 accessories and 2 platforms.
[6/19/2023, 12:02:33 PM] Loaded 0 cached accessories from cachedAccessories.
[6/19/2023, 12:02:33 PM] ---
[6/19/2023, 12:02:33 PM] Loaded plugin: homebridge-kevo@0.0.5
[6/19/2023, 12:02:33 PM] Registering accessory 'homebridge-kevo.Kevo'
[6/19/2023, 12:02:33 PM] ---
[6/19/2023, 12:02:33 PM] Loaded plugin: homebridge-konnected@1.3.1
[6/19/2023, 12:02:33 PM] Registering platform 'homebridge-konnected.konnected'
[6/19/2023, 12:02:33 PM] ---
[6/19/2023, 12:02:33 PM] Loaded plugin: homebridge-nest@4.6.9
[6/19/2023, 12:02:33 PM] Registering platform 'homebridge-nest.Nest'
[6/19/2023, 12:02:33 PM] ---
[6/19/2023, 12:02:33 PM] Loading 2 platforms...
[6/19/2023, 12:02:33 PM] [Nest] Initializing Nest platform...
[6/19/2023, 12:02:33 PM] [Nest] Initializing child bridge XXXXXX
[6/19/2023, 12:02:33 PM] Loading 1 accessories...
[6/19/2023, 12:02:33 PM] [Front Door] Initializing Kevo accessory...
Setup Payload:
X-HM://0023V5FEMIZZ2

**Comment by pmeisel123** [comment]
@danielsza / @mikeoc13  edit /var/lib/homebridge/node_modules/homebridge-kevo/index.js and change `www.mykevo.com` to `mykevo.com`

kevo has a bad ssl certificate on www.mykevo.com that is causing issues right now, but it is correct for `mykevo.com`

FYI this will be the last "fix" for me, I am tired of hacking homebridge-kevo to get it to work with Kevo's site regularly breaking.  The owner of this code gave up a long time ago

I am replacing my kevo locks with Level Lock+, which have homekit integration.

**Comment by mikeoc13** [comment]
> @danielsza / @mikeoc13 edit /var/lib/homebridge/node_modules/homebridge-kevo/index.js and change `www.mykevo.com` to `mykevo.com`
> 
> kevo has a bad ssl certificate on [www.mykevo.com](http://www.mykevo.com) that is causing issues right now, but it is correct for `mykevo.com`
> 
> FYI this will be the last "fix" for me, I am tired of hacking homebridge-kevo to get it to work with Kevo's site regularly breaking. The owner of this code gave up a long time ago
> 
> I am replacing my kevo locks with Level Lock+, which have homekit integration.

Thanks @danielsza that worked immediately.  I'm also looking at the Level Lock+, I just wish it came in a square form factor to match my door hardware.

**Comment by danielsza** [comment]
> @danielsza / @mikeoc13 edit /var/lib/homebridge/node_modules/homebridge-kevo/index.js and change `www.mykevo.com` to `mykevo.com`
> 
> kevo has a bad ssl certificate on [www.mykevo.com](http://www.mykevo.com) that is causing issues right now, but it is correct for `mykevo.com`
> 
> FYI this will be the last "fix" for me, I am tired of hacking homebridge-kevo to get it to work with Kevo's site regularly breaking. The owner of this code gave up a long time ago
> 
> I am replacing my kevo locks with Level Lock+, which have homekit integration.

Thank you @pmeisel123 this fixed the issue.
At some point I'll probably also look to replace these locks with zwave ones.

**Comment by sabresoftware2021** [comment]
I can't find the path ../node_modules/homebridge-kevo/index.js

My ls command in /var/lib/homebridge/ shows no directory called node_modules

What am I doing wrong?

Also contemplating upgrading to Lock+, but I'm waiting for our Condo complex to do the planned door/window upgrades so I can install in the new doors.

Fortunately Kevo Shortcuts allow me to issue "Hey Siri" commands, but I don't get to see the lock status in the Home app (my preference when I'm trying to control devices silently).

**Comment by danielsza** [comment]
> I can't find the path ../node_modules/homebridge-kevo/index.js
> 
> My ls command in /var/lib/homebridge/ shows no directory called node_modules
> 
> What am I doing wrong?
> 
> Also contemplating upgrading to Lock+, but I'm waiting for our Condo complex to do the planned door/window upgrades so I can install in the new doors.
> 
> Fortunately Kevo Shortcuts allow me to issue "Hey Siri" commands, but I don't get to see the lock status in the Home app (my preference when I'm trying to control devices silently).

Depening how your running HomeBridge, it may be a different directory.

I'm running the official image. For me to make the change I've used 
sudo pico /var/lib/homebridge/node_modules/homebridge-kevo/index.js

**Comment by sabresoftware2021** [comment]
OK, found the path, fixed the file and restarted HomeBridge and it works again. When I'm away for a few days I might disable this plugin just in case the other URL decides to go bad, otherwise my whole HomeBridge gets interrupted.

Thanks

**Comment by danielsza** [comment]
> OK, found the path, fixed the file and restarted HomeBridge and it works again. When I'm away for a few days I might disable this plugin just in case the other URL decides to go bad, otherwise my whole HomeBridge gets interrupted.
> 
> Thanks

Setup each plugin on a child bridge. That will keep one plugin from crashing any other.

**Comment by sabresoftware2021** [comment]
OK, good to know. Thx

**Comment by Spacebreathr** [comment]
I can’t seem to find the file to edit www.mykevo.com to mykevo.com in anywhere on my Mac. How do you access it? I can’t find it with the go to function in finder, in search or in the user folder.

**Comment by danielsza** [comment]
You’ll have to use terminal to access the directory/ file.Sent from my iPhoneOn Jul 3, 2023, at 15:45, Spacebreathr ***@***.***> wrote:﻿
I can’t seem to find the file to edit www.mykevo.com to mykevo.com in anywhere on my Mac. How do you access it? I can’t find it with the go to function in finder, in search or in the user folder.

**Comment by Spacebreathr** [comment]
How would you do that in this case? I saw the above comments, but I don’t quite understand how to navigate the UI.

**Comment by danielsza** [comment]
> How would you do that in this case? I saw the above comments, but I don’t quite understand how to navigate the UI.

It’s been a few years since I ran homebridge on macOS , but if I recall it  should be in /usr/local/lib/node_modules/homebridge-kevo/index.js

so open terminal and try 

sudo pico /usr/local/lib/node_modules/homebridge-kevo/index.js


Alternatively (assuming that the directory is correct )

download the updated file and copy it to the directory. ( you can find it my pull request) That way you don’t need to make the modifications yourself.

**Comment by sabresoftware2021** [comment]
That’s where I found the file on my Raspberry Pi. ---------------------------------------------Andrew Johnson, P.Eng.Sabre Software & Consulting Ltd. http://sabresoft.comOn Jul 3, 2023, at 19:20, danielsza ***@***.***> wrote:﻿

How would you do that in this case? I saw the above comments, but I don’t quite understand how to navigate the UI.

It’s been a few years since I ran homebridge on macOS , but if I recall it  should be in /usr/local/lib/node_modules/homebridge-kevo/index.js
so open terminal and try
sudo pico /usr/local/lib/node_modules/homebridge-kevo/index.js
Alternatively (assuming that the directory is correct )
download the updated file and copy it to the directory. ( you can find it my pull request) That way you don’t need to make the modifications yourself.

**Comment by sabresoftware2021** [comment]
That path is where I found it on my Raspberry Pi.

**Comment by Tiger519** [comment]
@sabresoftware2021 if you open the editor for index.js at that path you can change all of the www.mykevo.com urls to mykevo.com. I have contributor access so I'll see if I can figure out how to merge the pull requests and get a new version on npm. I may also see if I can add optional chaining to the response variable. This broke right before I went on vacation and did that so at least the response was undefined instead of throwing an uncaught exception and crashing homebridge (or child bridge if you have it set up that way, but I didn't want one child bridge per lock...).
